#!/usr/bin/env bash
# PreToolUse hook for Edit|Write|MultiEdit. Blocks edits to protected files:
# .env files, committed Alembic migrations, lockfiles. Exit 2 to block.
set -euo pipefail

input=$(cat)
path=$(printf '%s' "$input" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("tool_input",{}).get("file_path",""))')

[[ -z "$path" ]] && exit 0

reject() {
  printf 'BLOCKED by protect-files.sh: %s\n' "$1" >&2
  exit 2
}

case "$path" in
  */.env|*/.env.local|*/.env.production|*/.env.development|*/.env.test)
    reject "Edits to $path are not allowed. Modify .env.example instead and let the user copy." ;;
  */alembic/versions/*.py)
    reject "Cannot edit committed migration $path. Create a new migration: uv run alembic revision --autogenerate -m '<msg>'" ;;
  */package-lock.json|*/uv.lock|*/yarn.lock|*/pnpm-lock.yaml|*/poetry.lock)
    reject "Lockfile $path must be regenerated by its package manager (npm/uv/yarn/pnpm/poetry), not edited by hand." ;;
esac

exit 0
